{{ if .Values.cloudsql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.cloudsql.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.cloudsql.service.name }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.cloudsql.service.name }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.1
        imagePullPolicy: IfNotPresent
        command:
        - "/cloud_sql_proxy"
        - {{ $.Values.cloudsql.commandline.args | quote }}
        ports:
          - name: tcp
            containerPort: 5432
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
