apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "substrate-runtime-exporter.fullname" . }}
  labels:
    {{- include "substrate-runtime-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "substrate-runtime-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "substrate-runtime-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "substrate-runtime-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: runtime-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.service.port | quote }}
          - name: WS_PROVIDER
            value: {{ .Values.runtimeExporter.wsProvider }}
          - name: LOG_LEVEL
            value: {{ .Values.runtimeExporter.logLevel }}
          ports:
            - name: exporter
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: exporter
          readinessProbe:
            httpGet:
              path: /
              port: exporter
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
